### ISSUE TITLE
No image rendered in latest version of VSCode

### ISSUE THREAD

**Issue by Ran4** [geeklearningio/graphviz-markdown-preview#2]
Things worked great with the last version of VSCode, but as of the last version of VSCode, the plugin no longer renders an image.

VSCode info:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by sandorfr** [comment]
Similar issue on similar plugin. It seems it's a problem with VSCode itself. The documentation hasn't changed https://code.visualstudio.com/docs/extensionAPI/api-markdown .
https://github.com/mjbvz/vscode-markdown-mermaid/issues/15

**Comment by sandorfr** [comment]
This was indeed a bug in VS Code itself. the patch has been released. Just update vs code ;)

https://github.com/Microsoft/vscode/issues/45007
